name: cierreProyecto
entryPoint: main
runtime: python310
trigger: http
memory: 256MB
timeout: 60s
env_variables:
  JIRA_EMAIL: "mauricio.mendez@nubemsystems.es"
  JIRA_API_TOKEN: "YOUR_JIRA_API_TOKEN_HERE"
  JIRA_URL: "https://tuinstancia.atlassian.net"
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "noreply@nubemsystems.es"
  SMTP_PASSWORD: "YOUR_SMTP_PASSWORD_HERE"
