openapi: 3.0.0
info:
  title: NubemFlow - Exportador de Proyectos
  description: Endpoint para generar archivo ZIP con todos los elementos de un proyecto.
  version: 1.0.0

paths:
  /generarZipProyecto:
    post:
      summary: Generar ZIP de entrega de proyecto
      description: Devuelve un archivo ZIP con contexto, tareas, incidencias e informe técnico del proyecto indicado.
      operationId: generar_zip_proyecto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                proyecto:
                  type: string
                  example: Residencia Universitaria UB Campus Bellvitge
              required:
                - proyecto
      responses:
        '200':
          description: ZIP generado exitosamente
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Solicitud incorrecta
        '404':
          description: Proyecto no encontrado

servers:
  - url: https://europe-west1-nubemflow-prod.cloudfunctions.net
